name: ESLint

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
    #   - name: Run ESLint
    #     run: npx eslint . --ignore-pattern='*.js'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint .
